Controllers/DocumentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;

namespace FINALP2.Controllers
{

    [Authorize]
    public class DocumentoController : Controller
    {

        DocumentoNegocio documentoNegocio = new DocumentoNegocio();

        DepartamentoNegocio departamentoNegocio = new DepartamentoNegocio();

        UsuarioNegocio UsuarioNegocio = new UsuarioNegocio();

        // GET: Documento
        public ActionResult Index()
        {
            return View();
        }

        // GET: Documento/Details/5
        public ActionResult Details()
        {

            return View(documentoNegocio.ShowDocuments());
        }

        // GET: Documento/Create
        public ActionResult Create()
        {

            List<SelectListItem>
            Documentos = departamentoNegocio.ShowDepartments().ConvertAll(departamentoNegocio =>

        {
            return new SelectListItem()
            {
                Text = departamentoNegocio.Nombre.ToString(),
                Value = departamentoNegocio.ID.ToString(),
                Selected = false
            };
        });
            ViewBag.items = Documentos;


            List<SelectListItem>
            Usuarios = UsuarioNegocio.ShowUsers().ConvertAll(UsuarioNegocio =>

            {
                return new SelectListItem()
                {
                    Text = UsuarioNegocio.Nombre.ToString(),
                    Value = UsuarioNegocio.ID.ToString(),
                    Selected = false
                };
            });
            ViewBag.items1 = Usuarios;


            return View();
        }

        // POST: Documento/Create
        [HttpPost]
        public ActionResult Create(Documentos documentos)
        {

            documentoNegocio.CreateDocuments(documentos);

            return RedirectToAction("Details");
        }

        // GET: Documento/Edit/5
        public ActionResult Edit(int id)
        {
            return View(documentoNegocio.SelectDocuments(id));
        }

        // POST: Documento/Edit/5
        [HttpPost]
        public ActionResult Edit(Documentos documentos)
        {
            documentoNegocio.EditDocuments(documentos);

            return RedirectToAction("Details");

        }

        // GET: Documento/Delete/5
        public ActionResult Delete(int id)
        {
            return View(documentoNegocio.SelectDocuments(id));
        }

        // POST: Documento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection del)
        {
            documentoNegocio.DeleteDocuments(id);

            return RedirectToAction("Details");

        }

        public ActionResult DocumentsByRange(string Origin, string Destiny)
        {

            return View(documentoNegocio.DocumentsByRange(Origin, Destiny));

        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;

namespace FINALP2.Controllers
{

    [Authorize]
    public class UsuarioController : Controller
    {

        UsuarioNegocio usuarioNegocio = new UsuarioNegocio();

        DepartamentoNegocio departamentoNegocio = new DepartamentoNegocio();

        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        // GET: Usuario/Details/5
        public ActionResult Details()
        {
            return View(usuarioNegocio.ShowUsers());
        }

        // GET: Usuario/Create
        public ActionResult Create(){

            List<SelectListItem>
            Departamentos = departamentoNegocio.ShowDepartments().ConvertAll(departamentoNegocio =>

            {
                return new SelectListItem()
                {
                    Text = departamentoNegocio.Nombre.ToString(),
                    Value = departamentoNegocio.ID.ToString(),
                    Selected = false
                };
            });
            ViewBag.items = Departamentos;


            return View();
        }

        // POST: Usuario/Create
        [HttpPost]
        public ActionResult Create(Usuarios usuario){


            usuarioNegocio.CreateUsers(usuario);
                    
                // TODO: Add insert logic here

                return RedirectToAction("Details");
           
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            return View(usuarioNegocio.usersEdit(id));
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult Edit(Usuarios usuario)
        {
            usuarioNegocio.Edit(usuario);
            
                // TODO: Add update logic here

                return RedirectToAction("Details");
            
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int id)
        {
            return View(usuarioNegocio.usersEdit(id));
        }

        // POST: Usuario/Delete/5
        [HttpPost]
        public ActionResult Delete(Usuarios usuario)
        {
            usuarioNegocio.Delete(usuario);

                // TODO: Add delete logic here

                return RedirectToAction("Details");
            
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  rel="stylesheet" href="~/Content/Loginstyles.css"/>
    
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

</head>
        

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VipeTech", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    @*<li>@Html.ActionLink("Usuarios", "Details", "Usuario")</li>
                    <li>@Html.ActionLink("Departamentos", "Details", "Departamentos")</li>
                    <li>@Html.ActionLink("Documentos", "Details", "Documento")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Developed by: Marlon Villalona. All rights reserved.</p>
        </footer>*@ 
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false) 
</body>
</html>